# Generated by Django 4.1.4 on 2022-12-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100),
        ),
    ]
