# Generated by Django 4.1.4 on 2022-12-29 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_rating_choice_book_bookcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occupation', models.CharField(choices=[('писатель', 'писатель'), ('критик', 'критик'), ('издатель', 'издатель')], max_length=100)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpertRecomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('book_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_exp_rec', to='book.book')),
                ('expert_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp', to='book.expert')),
            ],
        ),
    ]
