# Generated by Django 4.1.4 on 2023-01-03 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_expert_expertrecomendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertrecomendation',
            name='book_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_recomendation', to='book.book'),
        ),
        migrations.AlterField(
            model_name='expertrecomendation',
            name='expert_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_name', to='book.expert'),
        ),
    ]
